# Uvoz funkcij, ki jih bomo potrebovali

library(knitr)
library(readr)
library(gsubfn)
library(tidyr)
library(xml2)
library(proto)
library(stringr)
library(rvest)
library(gridExtra)
library(readxl)
library(ggplot2)
library(graphics)
library(lattice)
